version: '3.8'

services:
  app:
    build:
      context: dockerfiles
      dockerfile: php.dockerfile
    container_name: laravel_app_php
    volumes:
      - ./Test_Laravel:/var/www/laravel
    ports:
      - '8010:8010'

    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql_db_php
    ports:
      - "3317:3306"
    environment:
      MYSQL_DATABASE: DB_laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
